/**
 * One-time environment setup.
 *
 *   node tools/setup-env.mjs          # create anything missing
 *   node tools/setup-env.mjs --force  # rewrite both files from scratch
 *
 * Creates `backend/.env` and `frontend/.env.local` with freshly generated
 * secrets. The secrets are generated here on your machine — they are not
 * copied from anywhere, and the files are git-ignored.
 *
 * Google sign-in is left blank on purpose: the site runs fine without it and
 * the button simply stays hidden until you fill those two values in.
 */

import { randomBytes } from "node:crypto";
import { readFile, writeFile, access } from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import readline from "node:readline/promises";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FORCE = process.argv.includes("--force");

const hex = (bytes) => randomBytes(bytes).toString("hex");
const b64 = (bytes) => randomBytes(bytes).toString("base64");

const exists = (p) =>
  access(p, constants.F_OK).then(
    () => true,
    () => false
  );

async function ask(question, fallback) {
  // Non-interactive (CI, or piped input): take the default without blocking.
  if (!process.stdin.isTTY) return fallback;
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const answer = (await rl.question(`${question} [${fallback}] `)).trim();
  rl.close();
  return answer || fallback;
}

async function main() {
  const backendEnv = path.join(ROOT, "backend", ".env");
  const frontendEnv = path.join(ROOT, "frontend", ".env.local");

  const backendExists = await exists(backendEnv);
  const frontendExists = await exists(frontendEnv);

  if (backendExists && frontendExists && !FORCE) {
    console.log(`
  ✅  Both environment files already exist:
        backend/.env
        frontend/.env.local

      Pass --force to regenerate them (this replaces your secrets).
`);
    return;
  }

  console.log("\n  🔐  Setting up your environment files…\n");

  const mongoUri = await ask(
    "  MongoDB connection string",
    "mongodb://127.0.0.1:27017/mobile-shop"
  );
  const apiPort = await ask("  Backend port", "5000");
  const siteUrl = await ask("  Frontend URL", "http://localhost:3000");

  // One shared value, written into both files — this is what lets the Next.js
  // auth layer prove itself to the API when a Google user signs in.
  const bridgeSecret = hex(32);

  const backendContent = `# Generated by \`npm run setup\` — safe to edit by hand.

# ---- server ----
NODE_ENV=development
PORT=${apiPort}

# ---- database ----
MONGODB_URI=${mongoUri}

# ---- auth ----
JWT_SECRET=${hex(48)}
JWT_EXPIRES_IN=30d

# Must stay identical to AUTH_BRIDGE_SECRET in frontend/.env.local
OAUTH_SHARED_SECRET=${bridgeSecret}

# ---- cors ----
CLIENT_URLS=${siteUrl}
`;

  const frontendContent = `# Generated by \`npm run setup\` — safe to edit by hand.

# ---- api ----
NEXT_PUBLIC_API_URL=http://localhost:${apiPort}/api
NEXT_PUBLIC_SITE_URL=${siteUrl}

# ---- Auth.js ----
AUTH_SECRET=${b64(32)}

# Must stay identical to OAUTH_SHARED_SECRET in backend/.env
AUTH_BRIDGE_SECRET=${bridgeSecret}

# ---- Google sign-in (optional) ----
# Leave these blank and the Google button stays hidden; email/password still
# works. To enable it:
#   1. https://console.cloud.google.com/apis/credentials
#      → Create credentials → OAuth client ID → Web application
#   2. Authorised JavaScript origins:  ${siteUrl}
#   3. Authorised redirect URIs:       ${siteUrl}/api/auth/callback/google
#   4. Paste the two values below and restart \`npm run dev\`.
AUTH_GOOGLE_ID=
AUTH_GOOGLE_SECRET=
`;

  const written = [];

  if (!backendExists || FORCE) {
    await writeFile(backendEnv, backendContent);
    written.push("backend/.env");
  }
  if (!frontendExists || FORCE) {
    await writeFile(frontendEnv, frontendContent);
    written.push("frontend/.env.local");
  }

  // Sanity check: if only one file was (re)generated, the shared secret in the
  // two files no longer matches, and Google sign-in would fail confusingly.
  if (written.length === 1) {
    const other = written[0] === "backend/.env" ? frontendEnv : backendEnv;
    const otherText = await readFile(other, "utf8");
    const key = written[0] === "backend/.env" ? "AUTH_BRIDGE_SECRET" : "OAUTH_SHARED_SECRET";
    const match = otherText.match(new RegExp(`^${key}=(.*)$`, "m"));
    if (match && match[1].trim() && match[1].trim() !== bridgeSecret) {
      console.log(`
  ⚠️   ${written[0]} was created, but the other file already existed with a
      different shared secret. Copy ${key}'s value across so both
      files match, or re-run with --force to regenerate both.`);
    }
  }

  console.log(`
  ✅  Wrote ${written.join(" and ")}

  Next:
      1.  Make sure MongoDB is running
          (${mongoUri})
      2.  cd backend  && npm install && npm run seed && npm run dev
      3.  cd frontend && npm install && npm run dev
      4.  Open ${siteUrl}

      Google sign-in is optional — see the comments in frontend/.env.local.
`);
}

main().catch((error) => {
  console.error("  ❌  Setup failed:", error);
  process.exit(1);
});
